# Generated by Django 2.1.5 on 2019-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kingdom', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=150)),
                ('common_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('intro', models.TextField(max_length=300)),
            ],
        ),
    ]
