# Generated by Django 2.1.5 on 2019-03-19 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('energy_source', models.CharField(choices=[('F', 'Food'), ('W', 'Water'), ('S', 'Snack'), ('L', 'Sunlight')], default='F', max_length=1)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='White', max_length=30)),
                ('style', models.CharField(choices=[('B', 'Blanket'), ('P', 'Pillow'), ('A', 'Apartment'), ('C', 'Condo'), ('H', 'House'), ('T', 'Aquarium'), ('L', 'Clay Pot'), ('V', 'Vase'), ('E', 'Petri Dish')], default='B', max_length=1)),
                ('size', models.CharField(choices=[('T', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'Extra Large'), ('H', 'Huge')], default='T', max_length=1)),
            ],
            options={
                'ordering': ['style'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kingdom', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=150)),
                ('common_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('height', models.IntegerField(verbose_name='Height (in)')),
                ('weight', models.FloatField(verbose_name='Weight (lbs)')),
                ('intro', models.TextField(max_length=300)),
                ('heaven', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pet'),
        ),
        migrations.AddField(
            model_name='energy',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pet'),
        ),
    ]
