# Generated by Django 2.1.5 on 2019-03-13 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('energy_source', models.CharField(choices=[('F', 'Food'), ('W', 'Water'), ('S', 'Snack'), ('L', 'Sunlight')], default='F', max_length=1)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pet')),
            ],
        ),
    ]
