# Generated by Django 2.1.5 on 2019-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='height',
            field=models.FloatField(verbose_name='Height (in)'),
        ),
    ]
