# Generated by Django 2.1.5 on 2019-03-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pet_heaven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='height',
            field=models.IntegerField(verbose_name='Height (in)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(verbose_name='Weight (lbs)'),
        ),
    ]
