# Generated by Django 2.1.5 on 2019-03-14 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20190313_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energy',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='pet',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
