# Generated by Django 2.1.5 on 2019-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190314_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necessity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='necessities',
            field=models.ManyToManyField(to='main_app.Necessity'),
        ),
    ]
